- app.js
- helpers/apiHelpers.js
- schemas/friendModel.js
привіт, схема монгуз, і виправила в арр шлях, бо не працювало
> Friend schema

- app.js
- helpers/apiHelpers.js
- models/friends.js
- routes/api/friends.js
- schemas/friendModel.js
- services/friendsService.js
так, код є, але в постмані вертає пустий массив, перевір будь ласка, чи є френдси у базі, бо я залила через атлас, а воно може в саму базу не дійшло, а якщо є, чи прийдуть ті френдси тобі у реквесті, пліз
> Friend controller route

- app.js
- controllers/auth/index.js
- controllers/auth/register.js
- controllers/index.js
- middlewares/index.js
- middlewares/validation.js
- package-lock.json
- package.json
- routes/api/auth.js
- schemas/friendModel.js
- schemas/userSchema.js
> register form

- app.js
- models/notices/getNoticesByCategory.js.js
- models/notices/index.js
- routes/api/notice.js
створено ендпоінт пошуку по категоріям
> Notice start

- models/notices/getNoticesBySearch.js
- models/notices/index.js
- routes/api/notice.js
ендпоінт notices/sell/dog пошук по слову в заголовку.
> Notice search

- schemas/userModel.js
add demands for login's page fields
> login schems demands

- models/notices/addNotice.js
- models/notices/getNoticeById.js
- routes/api/notice.js
додавання нотіс авторизованим користувачем, та фикс пошуку по ід щоб видав контакти овнера
> Notice add

- schemas/userModel.js
deleted birthday from userschema+ fixed regex(works correctly in english+ukrainian)
> fix userschema

- controllers/auth/login.js
- routes/api/auth.js
- schemas/userModel.js
fixed login, add joischema for updatedUser
> fix updateUser

- app.js
- package-lock.json
- package.json
- swagger.json
> start work

- controllers/auth/login.js
- routes/api/auth.js
- schemas/userModel.js
- schemas/validationJoi.js
Deleted login expired, add to schema field favorite, joi validation move to separate file
> login+schema user

- controllers/auth/currentUser.js
- controllers/auth/index.js
- controllers/auth/updateUser.js
- routes/api/auth.js
add fields to updateuser+ create a route for current user(for user+pets) route
> get current user and fixed updated user

- schemas/validationJoi.js
fixed databitrh for format 00-00-0000
> fix dta firmat

- controllers/pets/addPet.js
- controllers/pets/deletePet.js
- controllers/pets/index.js
- routes/api/pets.js
route+comtroller for deleting a pet
> controller for delete pet

- controllers/auth/login.js
- controllers/auth/register.js
- controllers/auth/updateUser.js
- controllers/pets/deletePet.js
> deleted garbage

- controllers/pets/getAllUserPets.js
- controllers/pets/index.js
- routes/api/pets.js
route and controller where we can get all pets of one user
> all pets of one user

- controllers/auth/register.js
- controllers/auth/updateAvatar.js
- middlewares/cloudinaryUploadMiddleware.js
> token for registration

- controllers/notices/addNotice.js
- controllers/notices/addNoticeCloudinary.js
- controllers/notices/index.js
- helpers/cloudinary.js
- middlewares/cloudinaryUploadMiddleware.js
- middlewares/index.js
- routes/api/notice.js
прикрутила клодінарі, наш код не ламає
> Clodinary2

- controllers/auth/updateAvatar.js
- middlewares/cloudyupdate.js
- middlewares/index.js
> fix prosecc env

- controllers/notices/changeImg.js
- middlewares/cloudinaryUploadMiddleware.js
- routes/api/notice.js
супер фікс і новий роут змінв фото
> Cloudinary progress

- controllers/auth/updateAvatar.js
- middlewares/cloudyupdate.js
- middlewares/upload.js
> clean avatarUpdate
